api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        mime_types: ['multipart/form-data']
        json: ['application/merge-patch+json']
        html: ['text/html']
    swagger:
        versions: [3]
