controllers:
    resource: ../src/Controller/
    type: attribute


coop_tilleuls_forgot_password:
    resource: .
    type: coop_tilleuls_forgot_password
    prefix: '/forgot-password'


coop_tilleuls_forgot_password.get_token:
    path: /forgot-password/{tokenValue}
    methods: [ GET ]
    defaults:
        _controller: App\Controller\GetTokenController

# config/routes.yaml
# api_login_check:
#     path: /api/login